{{- if not .Values.postgresql.enabled }}
{{- if not .Values.externalPostgresql.existingSecret.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ printf "%s-%s" .Release.Name "db"  }}
  labels:
    {{- include "srecource.labels" . | nindent 4 }}
type: Opaque
data:
  db-password: {{ default "" .Values.externalPostgresql.password | b64enc | quote }}
{{- end }}
{{- end }}
